[build]
command = "npm run build"
publish = "build"   # إذا مشروعك Vite غيّرها إلى "dist"

[functions]
directory = "netlify/functions"

# صفحات ثابتة (تُقدَّم كما هي)
[[redirects]]
from = "/storage-advisor"
to = "/storage-advisor/index.html"
status = 200

[[redirects]]
from = "/storage-advisor/"
to = "/storage-advisor/index.html"
status = 200

[[redirects]]
from = "/en/storage-advisor"
to = "/en/storage-advisor/index.html"
status = 200

[[redirects]]
from = "/en/storage-advisor/"
to = "/en/storage-advisor/index.html"
status = 200

# fallback عام لكل صفحات React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
