[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/assets/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/static/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/storage-advisor"
  to = "/.netlify/functions/og-handler"
  status = 200
  force = true

# This rule should be last to ensure other redirects/headers are processed first
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/og-handler"
  status = 200

# Explicitly redirect non-existent directories to 404
[[redirects]]
  from = "/*/.+"
  to = "/404.html"
  status = 404


