import React, { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ChevronDown, Menu, X, ArrowUpRight } from 'lucide-react';

const Header = ({ language, setLanguage }) => {
  const [open, setOpen] = useState(false);
  const [solutionsOpen, setSolutionsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const location = useLocation();
  useEffect(() => { setOpen(false); setSolutionsOpen(false); }, [location.pathname]);
  useEffect(() => { const f=()=>setScrolled(window.scrollY>12); window.addEventListener('scroll',f); return()=>window.removeEventListener('scroll',f); }, []);
  const t=language==='tr'?{home:'Ana Sayfa',about:'Hakkımızda',solutions:'Çözümler',storage:'Veri Depolama',backup:'Yedekleme Hizmetleri',recovery:'Veri Kurtarma',advisor:'Depolama Danışmanı',contact:'İletişim',menu:'Menü'}:{home:'Home',about:'About',solutions:'Solutions',storage:'Data Storage',backup:'Backup Services',recovery:'Data Recovery',advisor:'Storage Advisor',contact:'Contact',menu:'Menu'};
  const links=[[t.storage,'/data-storage'],[t.backup,'/backup-services'],[t.recovery,'/data-recovery'],[t.advisor,'/storage-advisor']];
  return <><header className="fixed left-0 top-0 z-50 w-full px-3 pt-3"><div className={`mx-auto flex max-w-7xl items-center justify-between rounded-2xl border px-4 py-3 transition-all sm:px-5 ${scrolled?'border-slate-200 bg-white/95 shadow-lg backdrop-blur':'border-slate-200/80 bg-white/85 backdrop-blur-xl'}`}><Link to="/"><img src="/images/tekfin-logo.png" alt="TekFin Teknoloji" className="h-12 w-auto sm:h-14 md:h-16"/></Link>
  <nav className="hidden items-center gap-1 md:flex"><Link to="/" className="rounded-full px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">{t.home}</Link><Link to="/about-us" className="rounded-full px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">{t.about}</Link><div className="relative"><button onClick={()=>setSolutionsOpen(v=>!v)} className="flex items-center gap-1 rounded-full px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100">{t.solutions}<ChevronDown className={`h-4 w-4 transition ${solutionsOpen?'rotate-180':''}`}/></button>{solutionsOpen&&<div className="absolute left-0 top-full mt-2 w-64 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl">{links.map(([label,href])=><Link key={href} to={href} className="flex items-center justify-between rounded-xl px-3 py-2.5 text-sm text-slate-700 hover:bg-slate-50">{label}<ArrowUpRight className="h-4 w-4 text-slate-400"/></Link>)}</div>}</div><Link to="/contact" className="ml-2 rounded-full bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">{t.contact}</Link></nav>
  <div className="flex items-center gap-1.5"><button onClick={()=>setLanguage('tr')} className={`rounded-full px-2.5 py-1.5 text-[11px] font-bold ${language==='tr'?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-100'}`}>TR</button><button onClick={()=>setLanguage('en')} className={`rounded-full px-2.5 py-1.5 text-[11px] font-bold ${language==='en'?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-100'}`}>EN</button><button className="ml-1 rounded-full p-2 text-slate-800 hover:bg-slate-100 md:hidden" onClick={()=>setOpen(true)} aria-label={t.menu}><Menu className="h-5 w-5"/></button></div></div></header>
  {open&&<div className="fixed inset-0 z-[60] bg-slate-950/40 backdrop-blur-sm md:hidden" onClick={()=>setOpen(false)}><div className="absolute right-3 top-3 w-[calc(100%-1.5rem)] max-w-md rounded-3xl bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><img src="/images/tekfin-logo.png" alt="TekFin Teknoloji" className="h-12 w-auto sm:h-14"/><button onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><nav className="mt-6 space-y-1"><Link to="/" className="block rounded-xl px-4 py-3 font-medium hover:bg-slate-50">{t.home}</Link><Link to="/about-us" className="block rounded-xl px-4 py-3 font-medium hover:bg-slate-50">{t.about}</Link><button onClick={()=>setSolutionsOpen(v=>!v)} className="flex w-full items-center justify-between rounded-xl px-4 py-3 font-medium hover:bg-slate-50">{t.solutions}<ChevronDown className={`h-4 w-4 ${solutionsOpen?'rotate-180':''}`}/></button>{solutionsOpen&&<div className="ml-3 border-l border-slate-200 pl-3">{links.map(([label,href])=><Link key={href} to={href} className="block rounded-xl px-4 py-2.5 text-sm text-slate-600 hover:bg-slate-50">{label}</Link>)}</div>}<Link to="/contact" className="mt-3 flex items-center justify-center rounded-xl bg-slate-950 px-4 py-3 font-semibold text-white">{t.contact}</Link></nav></div></div>}
  <div className="h-[96px]"/></>;
};
export default Header;