import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, Database, HardDrive, CloudUpload, RotateCcw, ShieldCheck, Activity, Network, LockKeyhole, Check, Server, BookOpen } from 'lucide-react';
import Newsletter from './Newsletter';

const HomePage=({language})=>{
 const navigate=useNavigate(); const goContact=i=>navigate(`/contact?intent=${i}`);
 const t=language==='tr'?{
  eyebrow:'TEKFİN • BUSINESS DATA INFRASTRUCTURE',title:'İşletmeniz için daha sağlam bir veri altyapısı.',subtitle:'Verilerinizi doğru yapılandırın, güvenilir şekilde yedekleyin ve ihtiyaç anında geri yükleyin.',intro:'TekFin, büyüyen işletmeler için depolama, yedekleme ve veri kurtarma altyapısını birlikte tasarlar. Hedefimiz yalnızca veri saklamak değil, iş sürekliliğini destekleyen yönetilebilir bir yapı kurmaktır.',primary:'Ücretsiz Veri Risk Analizi',secondary:'Danışmanlık Talep Et',advisor:'Depolama Danışmanı',advisorCta:'Öneri Alın',solutionsTitle:'Verinin yaşam döngüsünü tek bir yapı içinde yönetin.',solutionsText:'Depolama, yedekleme ve kurtarma birlikte tasarlanması gereken tek bir veri altyapısının parçalarıdır.',protectionTitle:'Koruma, çözümün üzerine eklenmez. İçine yerleştirilir.',protectionText:'Güvenlik ve izleme, TekFin veri altyapısının tasarım katmanının parçasıdır.',whyTitle:'Teknik altyapıyı işletme ihtiyacıyla birleştiriyoruz.',ctaTitle:'Veri kaybı bir sürpriz olmak zorunda değil.',ctaText:'Mevcut veri altyapınızı birlikte değerlendirelim ve işletmeniz için uygulanabilir bir yol haritası oluşturalım.'
 }:{
  eyebrow:'TEKFİN • BUSINESS DATA INFRASTRUCTURE',title:'A stronger data foundation for your business.',subtitle:'Structure your data, back it up reliably, and restore it when your business needs it.',intro:'TekFin designs storage, backup, and recovery infrastructure as one connected system for growing businesses. The goal is not simply to store data, but to build a manageable foundation that supports continuity.',primary:'Free Data Risk Assessment',secondary:'Request Consultation',advisor:'Storage Advisor',advisorCta:'Get Recommendation',solutionsTitle:'Manage the data lifecycle as one system.',solutionsText:'Storage, backup, and recovery are parts of one data infrastructure that should be designed together.',protectionTitle:'Protection is not added on top. It is built in.',protectionText:'Security and monitoring are part of the TekFin data infrastructure design layer.',whyTitle:'We connect technical infrastructure to business requirements.',ctaTitle:'Data loss does not have to be a surprise.',ctaText:'Let us assess your current data infrastructure and define a practical path forward.'
 };
 const solutions=language==='tr'?[['Veri Depolama','Performans, kapasite ve büyüme ihtiyacınıza göre doğru depolama mimarisi.',HardDrive,'/data-storage'],['Yedekleme Hizmetleri','Otomatik ve çok katmanlı yedekleme yaklaşımı, izleme ve raporlama.',CloudUpload,'/backup-services'],['Veri Kurtarma','RTO/RPO hedefleri, kurtarma senaryoları ve geri yükleme doğrulaması.',RotateCcw,'/data-recovery']]:[['Data Storage','Storage architecture aligned with performance, capacity, and growth requirements.',HardDrive,'/data-storage'],['Backup Services','Automated, multi-layer backup with monitoring and reporting.',CloudUpload,'/backup-services'],['Data Recovery','RTO/RPO objectives, recovery scenarios, and restore verification.',RotateCcw,'/data-recovery']];
 const protection=language==='tr'?['Şifreleme ve güvenli veri işleme','Erişim kontrolü ve yetkilendirme','Yedekleme başarısızlığı için uyarılar','Disk / RAID sağlık takibi','Periyodik geri yükleme testi']:['Encryption and secure data handling','Access control and authorization','Alerts for backup failures','Disk / RAID health monitoring','Periodic restore testing'];
 const why=language==='tr'?[['Pratik uzmanlık','Depolama, yedekleme ve kurtarma süreçlerinde işletme odaklı yaklaşım.'],['Güvenilirlik','Veri gizliliği ve doğrulanabilir süreçler tasarımın merkezindedir.'],['Hızlı aksiyon','Kritik durumlarda net süreç ve uygulanabilir teknik çözüm.'],['İş sürekliliği','Erişilebilirlik, kurtarılabilirlik ve sürekliliğe odaklanırız.']]:[['Practical expertise','Business-focused experience across storage, backup, and recovery.'],['Reliability','Confidentiality and verifiable processes are built into the architecture.'],['Fast response','Clear processes and practical technical action when it matters.'],['Business continuity','We focus on availability, recoverability, and continuity.']];
 return <div className="bg-white text-slate-950">
  <section className="relative overflow-hidden bg-[#f7f7f4]"><div className="absolute inset-0 opacity-60" style={{backgroundImage:'linear-gradient(rgba(15,23,42,.045) 1px, transparent 1px),linear-gradient(90deg,rgba(15,23,42,.045) 1px,transparent 1px)',backgroundSize:'48px 48px'}}/><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:py-28"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-3 py-1.5 text-[11px] font-semibold tracking-[.16em] text-slate-600 shadow-sm"><span className="h-2 w-2 rounded-full bg-blue-600"/>{t.eyebrow}</div><h1 className="max-w-3xl text-4xl font-bold leading-[1.02] tracking-[-.04em] sm:text-5xl lg:text-[4.6rem]">{t.title}</h1><p className="mt-7 max-w-2xl text-lg font-medium leading-8 text-slate-700 sm:text-xl">{t.subtitle}</p><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-500 sm:text-base">{t.intro}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>goContact('assessment')} className="group inline-flex items-center justify-center rounded-full bg-slate-950 px-6 py-3.5 text-sm font-semibold text-white hover:bg-blue-700">{t.primary}<ArrowRight className="ml-2 h-4 w-4 transition group-hover:translate-x-1"/></button><button onClick={()=>goContact('consultation')} className="rounded-full border border-slate-300 bg-white px-6 py-3.5 text-sm font-semibold text-slate-900 hover:border-slate-950">{t.secondary}</button></div></div>
   <div className="relative mx-auto w-full max-w-xl"><div className="rounded-[2rem] border border-slate-200 bg-slate-950 p-3 shadow-2xl"><div className="rounded-[1.5rem] border border-white/10 bg-[#111827] p-5 sm:p-7"><div className="mb-7 flex items-center justify-between"><div><p className="text-[10px] font-semibold tracking-[.2em] text-slate-500">DATA INFRASTRUCTURE</p><p className="mt-1 text-sm font-semibold text-white">Business Continuity Layer</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1.5 text-[11px] font-semibold text-emerald-300">● {language==='tr'?'Koruma aktif':'Protection active'}</span></div><div className="grid grid-cols-2 gap-3"><div className="col-span-2 rounded-2xl border border-blue-400/20 bg-blue-400/10 p-5"><div className="flex items-center gap-3"><Network className="h-5 w-5 text-blue-300"/><div><p className="text-xs text-slate-400">CORE</p><p className="font-semibold text-white">Business Continuity</p></div></div></div>{[[Database,'Storage'],[CloudUpload,'Backup'],[RotateCcw,'Recovery'],[ShieldCheck,'Protection']].map(([I,l],i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><I className="h-5 w-5 text-blue-300"/><p className="mt-5 text-sm font-semibold text-white">{l}</p><p className="mt-1 text-[11px] text-slate-500">{language==='tr'?'Yönetilen katman':'Managed layer'}</p></div>)}</div><div className="mt-4 grid grid-cols-3 gap-3">{[[Activity,'Monitoring'],[LockKeyhole,'Access'],[Check,'Verification']].map(([I,l],i)=><div key={i} className="flex items-center gap-2 rounded-xl bg-white/[.035] px-3 py-2.5 text-[11px] font-medium text-slate-400"><I className="h-4 w-4 text-slate-300"/>{l}</div>)}</div></div></div><div className="absolute -bottom-5 -left-4 hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-xl sm:block"><div className="flex items-center gap-3"><Server className="h-5 w-5 text-blue-600"/><div><p className="text-[10px] text-slate-400">TEKFİN</p><p className="text-xs font-bold">Data Infrastructure</p></div></div></div></div>
  </div></section>
  <section className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-3 sm:grid-cols-3">{[['Storage',Database],['Backup',CloudUpload],['Recovery',RotateCcw]].map(([l,I],i)=><div key={i} className="flex items-center gap-3 rounded-2xl bg-slate-50 px-5 py-4"><I className="h-5 w-5 text-slate-700"/><span className="text-sm font-semibold">{language==='tr'?([ 'Depolama','Yedekleme','Kurtarma'][i]):l}</span><span className="ml-auto h-1.5 w-1.5 rounded-full bg-blue-600"/></div>)}</div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="max-w-3xl"><div className="mb-4 text-xs font-bold tracking-[.2em] text-blue-600">SOLUTIONS</div><h2 className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">{t.solutionsTitle}</h2><p className="mt-5 text-base leading-7 text-slate-500 sm:text-lg">{t.solutionsText}</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{solutions.map(([title,text,I,href],i)=><button key={i} onClick={()=>navigate(href)} className="group rounded-[1.75rem] border border-slate-200 bg-white p-7 text-left shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="mb-14 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-blue-600"><I className="h-6 w-6"/></div><div className="flex items-end justify-between gap-4"><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p></div><ArrowRight className="h-5 w-5 shrink-0 transition group-hover:translate-x-1"/></div></button>)}</div></section>
  <section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:py-28"><div><div className="mb-4 text-xs font-bold tracking-[.2em] text-blue-300">BUILT-IN PROTECTION</div><h2 className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">{t.protectionTitle}</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">{t.protectionText}</p></div><div className="grid gap-3 sm:grid-cols-2">{protection.map((x,i)=><div key={i} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><Check className="h-5 w-5 text-blue-300"/><p className="mt-6 text-sm font-semibold text-slate-100">{x}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><div className="mb-4 text-xs font-bold tracking-[.2em] text-blue-600">WHY TEKFIN</div><h2 className="text-3xl font-bold tracking-[-.03em] sm:text-5xl">{t.whyTitle}</h2></div><div className="grid gap-3 sm:grid-cols-2">{why.map(([a,b],i)=><div key={i} className="rounded-2xl border border-slate-200 p-6"><div className="mb-8 text-sm font-bold text-slate-400">0{i+1}</div><h3 className="font-bold">{a}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{b}</p></div>)}</div></div></section>
  <section className="bg-[#f7f7f4]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="flex flex-col gap-5 rounded-[2rem] border border-slate-200 bg-white p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-2 text-xs font-bold tracking-[.16em] text-slate-400"><BookOpen className="h-4 w-4"/> FUTURE SERVICES</div><p className="mt-3 text-sm leading-6 text-slate-600">{language==='tr'?'Managed Backup, Cloud DR ve Remote Monitoring gibi hizmetleri zaman içinde veri altyapısı portföyümüze ekleyeceğiz.':'Managed Backup, Cloud DR and Remote Monitoring capabilities will expand the data infrastructure portfolio over time.'}</p></div><button onClick={()=>navigate('/storage-advisor')} className="inline-flex shrink-0 items-center justify-center rounded-full bg-slate-950 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700">{t.advisor}<ArrowRight className="ml-2 h-4 w-4"/></button></div></div></section>
  <Newsletter language={language}/>
  <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div className="overflow-hidden rounded-[2rem] bg-blue-600 px-7 py-14 text-white sm:px-12 lg:px-16"><h2 className="max-w-3xl text-3xl font-bold tracking-[-.03em] sm:text-5xl">{t.ctaTitle}</h2><p className="mt-5 max-w-2xl leading-7 text-blue-100">{t.ctaText}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>goContact('assessment')} className="rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-blue-700 hover:bg-blue-50">{t.primary}</button><button onClick={()=>goContact('consultation')} className="rounded-full border border-white/30 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white">{t.secondary}</button></div></div></section>
 </div>;
};
export default HomePage;